site_name: Building Inclusive Open Source Software
site_url: https://alterity-git.github.io/building-inclusive-open-source-software/
site_author: Maxence Vahedi & Page Magnier--Slimani
site_description: >-
  Accessibility and inclusiveness resources and training modules for open-source applications builders.

repo_name: alterity-git/building-inclusive-open-source-software
repo_url: https://github.com/alterity-git/building-inclusive-open-source-software

copyright: Maxence Vahedi & Page Magnier--Slimani CC BY-SA 4.0

theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.footer
    - content.tabs.link
  name: material
  font:
    text:
  logo: resources/logo.png
  favicon: resources/logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: custom-dark
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - What is accessibility?:
    - ğŸš€ Accessibility starting point: A-ASP.md
    - ğŸ«³ğŸ¿ Feeling the need for accessibility: A-FNA.md
    - ğŸ‘©â€ğŸ¦½ Accessibility & Ableism: A-AIE.md
    - ğŸ—ºï¸ Brief cartography of todayâ€™s accessibility landscape: A-BCT.md
    - ğŸ”§ Assistive technologies - Desktop: A-ITD.md
    - ğŸ“² Assistive technologies - Mobile: A-ATM.md
  - From accessibility to inclusiveness:
    - ğŸ”­ Inclusiveness needs overview: B-INO.md
    - ğŸ«‚ We are all disabled and unique: B-WDU.md
    #- ğŸ›ï¸ Why does FOSS struggle with inclusiveness?:
    - ğŸ¤º Developer stance & user collaboration: B-DSU.md
    - âš—ï¸ Bring inclusiveness and accessibility to your pipeline: B-IAP.md
  - Designing inclusive and accessible software:
    - ğŸ¨ Inclusive design 101: C-IDE.md
    - ğŸ–¥ï¸ Inclusive design for Desktop: C-IDD.md
    - ğŸ“± Inclusive design for Mobile: C-IDM.md
  - Programming inclusive and accessible software:
    - ğŸ‘©â€ğŸ’» Inclusive code 101: D-ICO.md
    - ğŸ Inclusive features and programming for Apple platforms: D-APL.md
    - ğŸ“— Inclusive programming with Qt: D-APQ.md
    - ğŸ¤– Inclusive features and programming for Android: D-AND.md
    - â˜•ï¸ Inclusive programming with JavaFX: D-JFX.md
    - ğŸ•¸ï¸ Inclusive web programming: D-IWP.md
  - To conclude and go further:
    - ğŸ¯ Conclusion, bibliography and useful resources: E-CBU.md
    - ğŸƒğŸ½â€â™€ï¸â€â¡ï¸ Where YOU go next!: E-WYG.md
    - ğŸ’¬ Collective sharing: E-CLS.md

extra_css:
  - stylesheets/extra.css
