site_name: Building Inclusive Open Source Software
site_url: https://page-and-maxence.github.io/building-inclusive-open-source-software
site_author: Maxence Vahedi & Page Magnier--Slimani
site_description: >-
  Accessibility and inclusiveness resources and training modules for open-source applications builders.

repo_name: Page-and-Maxence/building-inclusive-open-source-software
repo_url: https://github.com/Page-and-Maxence/building-inclusive-open-source-software

copyright: Maxence Vahedi & Page Magnier--Slimani CC BY-SA 4.0

theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.footer
  name: material
  font:
    text:
  logo: ressources/logo.png
  favicon: ressources/logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: custom-dark
      toggle:
        icon: material/weather-night
        name: Switch to system preference

nav:
  - Home: index.md
  - What is accessibility?:
    - ğŸš€ Accessibility starting point: A-ASP.md
    - ğŸ«³ğŸ¿ Feeling the need for accessibility: A-FNA.md
    - ğŸ‘©â€ğŸ¦½ Accessibility & Ableism: A-AIE.md
    - ğŸ—ºï¸ Brief cartography of todayâ€™s accessibility landscape: A-BCT.md
    - ğŸ”§ Inclusiveness technologies Desktop: A-ITD.md
    #- ğŸ“² Accessibility technologies - mobile:
  - From accessibility to inclusiveness:
    - ğŸ«‚ We are all disabled and unique: B-WDU.md
    #- ğŸ›ï¸ Why does FOSS struggle with inclusiveness?:
    #- ğŸ”­ Inclusiveness needs overview: B-INO.md
    - ğŸ¤º Developer stance & user collaboration: B-DSU.md
    - âš—ï¸ Bring inclusiveness and accessibility to your pipeline: B-IAP.md
  - Designing inclusive and accessible software:
    - ğŸ¨ Inclusive design 101: C-IDE.md
    - ğŸ–¥ï¸ Inclusive design for Desktop: C-IDD.md
    #- ğŸ“± Inclusive design for Mobile:
  - Programming inclusive and accessible software:
    - ğŸ‘©â€ğŸ’» Inclusive code 101: D-ICO.md
    #- ğŸ Accessible programming for the Apple ecosystem:
    - ğŸ“— Accessible programming with Qt: D-APQ.md
    #- â˜•ï¸ Accessible programming with Java Fx:
    #- ğŸ¤– Accessible programming for Android:
    #- ğŸ•¸ï¸ Accessible web programming:
  - To conclude and go further:
    #- ğŸ¯ Conclusion, bibliography and useful resources:
    - ğŸƒğŸ½â€â™€ï¸â€â¡ï¸ Where YOU go next !: E-WYG.md
    - ğŸ’¬ Collective sharing: E-CLS.md

markdown_extensions:
  - admonition

extra_css:
  - stylesheets/extra.css
